//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicalOpinions
    {
        public int MedicalOpinionId { get; set; }
        public int OpinionId { get; set; }
        public int DoctorId { get; set; }
        public string Note { get; set; }
        public int MedCardId { get; set; }
        public Nullable<int> IllnessID { get; set; }
        public string NameDoctor
        {
            get
            {
                return App.CurrentUser.FIO;
            }
        }
        public string RoleName
        {
            get
            {
                return App.CurrentUser.RoleName;
            }
        }

        public virtual Illness Illness { get; set; }
        public virtual MedCard MedCard { get; set; }
        public virtual Opinion Opinion { get; set; }
        public virtual Users Users { get; set; }
    }
}
