//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VovaDiplomEntities : DbContext
    {
        public VovaDiplomEntities()
            : base("name=VovaDiplomEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<CategoryIllness> CategoryIllness { get; set; }
        public virtual DbSet<Illness> Illness { get; set; }
        public virtual DbSet<MedCard> MedCard { get; set; }
        public virtual DbSet<MedicalOpinions> MedicalOpinions { get; set; }
        public virtual DbSet<MilitaryTerritory> MilitaryTerritory { get; set; }
        public virtual DbSet<Opinion> Opinion { get; set; }
        public virtual DbSet<Recruit> Recruit { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
