//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom.Entities
{
    using System;
    using System.Collections.Generic;
    using System.IO;

    public partial class Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users()
        {
            this.MedicalOpinions = new HashSet<MedicalOpinions>();
        }
    
        public int UserId { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Patronymic { get; set; }
        public int RoleId { get; set; }
        public string Phone { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public byte[] Image { get; set; }
        public string RoleName
        {
            get
            {
                return Role.Role1.ToString();
            }
        }
        public string FIO
        {
            get
            {
                return Surname + " " + Name + " " + Patronymic;
            }
        }
        public byte[] UserImage
        {
            get
            {
                if (Image == null)
                    return File.ReadAllBytes("../../bin/Resources/user.jpg");
                else return Image;
            }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedicalOpinions> MedicalOpinions { get; set; }
        public virtual Role Role { get; set; }
    }
}
